deployment:
  tasks:
    - export REPO_DIR=$HOME/github/kleamerkuri/.git
    - export DEPLOY_DIR=$HOME/public_html/portfolios/kleamerkuri 
    - /bin/rm -rf $DEPLOY_DIR      
    - mkdir -p $DEPLOY_DIR                 
    - git --work-tree=$DEPLOY_DIR --git-dir=$REPO_DIR checkout gh-pages -- .
    - /bin/find $DEPLOY_DIR -type d -exec chmod 755 {} +  
    - /bin/find $DEPLOY_DIR -type f -exec chmod 644 {} +  