deployment:
  tasks:
    - export DEPLOY_DIR=$HOME/public_html/portfolios/kleamerkuri 
    - /bin/rm -rf $DEPLOY_DIR/*           # Clear existing files
    - git --work-tree=$DEPLOY_DIR checkout gh-pages -- . 
    - find $DEPLOY_DIR -type d -exec chmod 755 {} \;  # Set 0755 for directories
    - find $DEPLOY_DIR -type f -exec chmod 644 {} \;  # Set 0644 for files
